In [50]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
from pycaret.classification import *
from pycaret.datasets import get_data
from imblearn.over_sampling import SMOTE 
from imblearn.under_sampling import RandomUnderSampler
from imblearn.under_sampling import ClusterCentroids
mpl.rcParams['figure.dpi'] = 300
import sys
import warnings
import os

In [51]:
data = pd.read_csv("FinalData.csv")

In [52]:
data

,GenderID,Age,LastEduID,MET_Final,WaistCircumference,HipCircumference,WristCircumference,BMI,HasJob_new,Employmentstatus,...,HasChronicLungDisease,HasHepatitisC,HasHepatitisB,HasFattyLiver,HasRenalFailure,HasStroke,HasMI,HasCardiacDisease,HasHypertension,HasDiabetes
0,2,44,3,34.899995,116.0,120.0,19.0,36.652780,1,1,...,0,0,0,1,0,0,0,0,0,0
1,1,52,1,48.075000,99.0,105.0,18.0,28.256990,1,1,...,0,0,0,0,0,0,0,0,0,0
2,1,70,2,39.416654,89.0,94.0,16.0,20.973709,2,99999,...,0,0,0,0,0,0,0,1,0,0
3,2,70,8,51.175000,96.0,106.0,17.0,30.081371,0,999,...,0,0,0,0,0,1,0,0,1,0
4,2,47,1,34.841659,90.0,97.0,17.5,25.815689,3,99,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3198,2,58,8,40.991661,115.0,112.0,19.0,34.105851,3,99,...,0,0,0,0,0,0,0,0,1,0
3199,2,50,8,37.108330,94.0,99.0,16.0,24.878345,3,99,...,0,0,0,0,0,0,0,0,0,0
3200,2,65,8,39.700000,93.0,99.0,16.0,24.609734,3,99,...,0,0,0,0,0,1,0,0,1,0
3201,1,42,1,40.449995,97.0,96.0,18.0,23.999459,1,1,...,0,0,0,0,0,0,0,0,0,0
3202,2,38,3,39.508321,92.0,94.0,17.0,26.527905,3,99,...,0,0,0,0,0,0,0,0,0,0

In [53]:
data.describe()

,GenderID,Age,LastEduID,MET_Final,WaistCircumference,HipCircumference,WristCircumference,BMI,HasJob_new,Employmentstatus,...,HasChronicLungDisease,HasHepatitisC,HasHepatitisB,HasFattyLiver,HasRenalFailure,HasStroke,HasMI,HasCardiacDisease,HasHypertension,HasDiabetes
count,3203.000000,3203.000000,3203.000000,3203.000000,3203.000000,3203.000000,3203.000000,3203.000000,3203.000000,3203.000000,...,3203.000000,3203.000000,3203.000000,3203.000000,3203.000000,3203.000000,3203.000000,3203.000000,3203.000000,3203.000000
mean,1.568530,50.290665,4.001561,40.135049,97.835529,101.150328,17.953793,27.809414,1.960037,6523.606931,...,0.029035,0.000312,0.000312,0.215111,0.018108,0.019357,0.026225,0.091477,0.242897,0.125507
std,0.495359,9.702193,2.669664,5.490491,19.438126,9.208158,1.667830,5.039845,1.033010,24398.873936,...,0.167932,0.017669,0.017669,0.410963,0.133363,0.137797,0.159830,0.288331,0.428900,0.331345
min,1.000000,35.000000,1.000000,23.599995,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,42.000000,2.000000,36.774998,90.000000,95.000000,17.000000,24.430611,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2.000000,50.000000,3.000000,39.308323,97.000000,100.000000,18.000000,27.428571,2.000000,99.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2.000000,58.000000,8.000000,42.527078,105.000000,106.000000,19.000000,30.676944,3.000000,99.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,2.000000,70.000000,8.000000,80.549996,958.000000,146.000000,29.000000,54.862351,3.000000,99999.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [54]:
data['HasDiabetes'].value_counts()

HasDiabetes
0    2801
1     402
Name: count, dtype: int64

In [55]:
round(data.HasDiabetes.value_counts()*100/len(data),2)

HasDiabetes
0    87.45
1    12.55
Name: count, dtype: float64

In [56]:
data.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3203 entries, 0 to 3202
Data columns (total 111 columns):
 #    Column                    Dtype
---   ------                    -----
 0    GenderID                  int64
 1    Age                       int64
 2    LastEduID                 int64
 3    MET_Final                 float64
 4    WaistCircumference        float64
 5    HipCircumference          float64
 6    WristCircumference        float64
 7    BMI                       float64
 8    HasJob_new                int64
 9    Employmentstatus          int64
 10   SleepDuration24h1         float64
 11   SleepDurationMidDay1      float64
 12   TV1                       float64
 13   AtDeskWork1               float64
 14   Computer1                 float64
 15   Eating1                   float64
 16   Cooking1                  float64
 17   Driving1                  float64
 18   Walking1                  float64
 19   AerobicExercise1          float64
 20   DrivingHeavyVehicle1      float64
 21   LightTechnicalJobs1       float64
 22   LightAgricultural1        float64
 23   HeavyLaborAgricultJobs1   float64
 24   HeavyExercise1            float64
 25   DPB                       int64
 26   SPB                       int64
 27   RBC                       float64
 28   HGB                       float64
 29   FBS                       int64
 30   TG                        int64
 31   CHOL                      int64
 32   SGOT                      int64
 33   SGPT                      float64
 34   ALP                       int64
 35   HDL.C                     float64
 36   GGT                       float64
 37   LDL_Calc                  float64
 38   WSI_total                 float64
 39   UseDrugs                  int64
 40   UseAlcohol                int64
 41   Pizza                     float64
 42   TEACOFFEE                 float64
 43   BAVARAGE                  float64
 44   Pickle                    float64
 45   Oil                       float64
 46   SimpleSugar               float64
 47   Vegetables                float64
 48   Nuts                      float64
 49   Juice                     float64
 50   Fruits                    float64
 51   Legumes                   float64
 52   Whitemeat                 float64
 53   Redmeat                   float64
 54   Totalmeat                 float64
 55   dairyproduct              float64
 56   Wholegrain                float64
 57   Nutrient FFQ_protein      float64
 58   Total_lipid_fat           float64
 59   GrilledFoodIntID          int64
 60   FriedFoodIntID            int64
 61   PotatoFryTypeID           int64
 62   VegFryTypeID              int64
 63   UsedOilTypeID             int64
 64   ReUseMold                 int64
 65   SmokedFoodIntID           int64
 66   FreezMeatTypeID           int64
 67   UsedScratchedTeflon       int64
 68   FoodSaltUsedID            int64
 69   OnionFryTypeID            int64
 70   CookingWareID1            int64
 71   VegKeepDried              int64
 72   VegKeepRefrigerator       int64
 73   VegKeepFreezer            int64
 74   VegKeepFresh              int64
 75   BreadContainerTypeID1     int64
 76   LemonContainerTypeID1     int64
 77   CVD_History               int64
 78   HasPregnancyHypertension  int64
 79   HasMS                     int64
 80   HasLupus                  int64
 81   HasOvarianCancer          int64
 82   HasTongueCancer           int64
 83   HasLaryngealCancer        int64
 84   HasAmnesia                int64
 85   HasDepression             int64
 86   HasEpilepsy               int64
 87   HasBrainAndCNSCancer      int64
 88   HasLungCancer             int64
 89   HasProstateCancer         int64
 90   HasEsophagusCancer        int64
 91   HasHSC                    int64
 92   HasBladderCancer          int64
 93   HasColorectalCancer       int64
 94   HasStomachCancer          int64
 95   HasBreastCancer           int64
 96   HasSkinCancer             int64
 97   HasRheumaticDisease       int64
 98   HasGallstone              int64
 99   HasKidneyStone            int64
 100  HasThyroidDisease         int64
 101  HasChronicLungDisease     int64
 102  HasHepatitisC             int64
 103  HasHepatitisB             int64
 104  HasFattyLiver             int64
 105  HasRenalFailure           int64
 106  HasStroke                 int64
 107  HasMI                     int64
 108  HasCardiacDisease         int64
 109  HasHypertension           int64
 110  HasDiabetes               int64
dtypes: float64(45), int64(66)
memory usage: 2.7 MB

In [57]:
round(data.isnull().sum().sort_values(ascending=False)*100/len(data),2)

Pizza               0.03
GenderID            0.00
Wholegrain          0.00
HasOvarianCancer    0.00
HasLupus            0.00
                    ...
SGPT                0.00
SGOT                0.00
CHOL                0.00
TG                  0.00
HasDiabetes         0.00
Length: 111, dtype: float64

In [58]:
data.nunique()

GenderID                 2
Age                     36
LastEduID                8
MET_Final             2953
WaistCircumference     167
                      ...
HasStroke                2
HasMI                    2
HasCardiacDisease        2
HasHypertension          2
HasDiabetes              2
Length: 111, dtype: int64

In [59]:
data.shape

(3203, 111)

In [60]:
data.columns

Index(['GenderID', 'Age', 'LastEduID', 'MET_Final', 'WaistCircumference',
       'HipCircumference', 'WristCircumference', 'BMI', 'HasJob_new',
       'Employmentstatus',
       ...
       'HasChronicLungDisease', 'HasHepatitisC', 'HasHepatitisB',
       'HasFattyLiver', 'HasRenalFailure', 'HasStroke', 'HasMI',
       'HasCardiacDisease', 'HasHypertension', 'HasDiabetes'],
      dtype='object', length=111)

In [61]:
if not sys.warnoptions:
    warnings.simplefilter("ignore")
    os.environ["PYTHONWARNINGS"] = "ignore" # Also affect subprocesses

In [62]:
data

,GenderID,Age,LastEduID,MET_Final,WaistCircumference,HipCircumference,WristCircumference,BMI,HasJob_new,Employmentstatus,...,HasChronicLungDisease,HasHepatitisC,HasHepatitisB,HasFattyLiver,HasRenalFailure,HasStroke,HasMI,HasCardiacDisease,HasHypertension,HasDiabetes
0,2,44,3,34.899995,116.0,120.0,19.0,36.652780,1,1,...,0,0,0,1,0,0,0,0,0,0
1,1,52,1,48.075000,99.0,105.0,18.0,28.256990,1,1,...,0,0,0,0,0,0,0,0,0,0
2,1,70,2,39.416654,89.0,94.0,16.0,20.973709,2,99999,...,0,0,0,0,0,0,0,1,0,0
3,2,70,8,51.175000,96.0,106.0,17.0,30.081371,0,999,...,0,0,0,0,0,1,0,0,1,0
4,2,47,1,34.841659,90.0,97.0,17.5,25.815689,3,99,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3198,2,58,8,40.991661,115.0,112.0,19.0,34.105851,3,99,...,0,0,0,0,0,0,0,0,1,0
3199,2,50,8,37.108330,94.0,99.0,16.0,24.878345,3,99,...,0,0,0,0,0,0,0,0,0,0
3200,2,65,8,39.700000,93.0,99.0,16.0,24.609734,3,99,...,0,0,0,0,0,1,0,0,1,0
3201,1,42,1,40.449995,97.0,96.0,18.0,23.999459,1,1,...,0,0,0,0,0,0,0,0,0,0
3202,2,38,3,39.508321,92.0,94.0,17.0,26.527905,3,99,...,0,0,0,0,0,0,0,0,0,0

In [63]:
X = data.drop(columns='HasDiabetes')
y = data.HasDiabetes
from sklearn.impute import SimpleImputer
freq_imputer = SimpleImputer(strategy='most_frequent')
X_freq_imputed = pd.DataFrame(freq_imputer.fit_transform(X))
X_freq_imputed.columns = X.columns

In [64]:
from sklearn.feature_selection import VarianceThreshold
threshold_n=0.95
sel = VarianceThreshold(threshold=(threshold_n* (1 - threshold_n) ))
sel_var=sel.fit_transform(X_freq_imputed)
X_freq_imputed=X_freq_imputed[X_freq_imputed.columns[sel.get_support(indices=True)]]

In [16]:
print("Before Sampling, counts of label '1': {}".format(sum(y == 1))) 
print("Before Sampling, counts of label '0': {} \n".format(sum(y == 0)))

sm = SMOTE(random_state = 123) 
X_resampled, y_resampled  = sm.fit_resample(X_freq_imputed, y.ravel())
#cc = ClusterCentroids(random_state=123)
#X_resampled, y_resampled  = cc.fit_resample(X_freq_imputed, y.ravel())

#rus = RandomUnderSampler(random_state=123)
#X_resampled, y_resampled  = rus.fit_resample(X_freq_imputed, y)

print('After Sampling, the shape of train_X: {}'.format(X_resampled.shape)) 
print('After Sampling, the shape of train_y: {} \n'.format(y_resampled.shape)) 
  
print("After Sampling, counts of label '1': {}".format(sum(y_resampled == 1))) 
print("After Sampling, counts of label '0': {}".format(sum(y_resampled == 0)))

Before Sampling, counts of label '1': 402
Before Sampling, counts of label '0': 2801

After Sampling, the shape of train_X: (5602, 79)
After Sampling, the shape of train_y: (5602,)

After Sampling, counts of label '1': 2801
After Sampling, counts of label '0': 2801

In [65]:
X_resampled=X_freq_imputed
y_resampled=y.ravel()

In [66]:
X_resampled

,GenderID,Age,LastEduID,MET_Final,WaistCircumference,HipCircumference,WristCircumference,BMI,HasJob_new,Employmentstatus,...,VegKeepFreezer,BreadContainerTypeID1,LemonContainerTypeID1,CVD_History,HasDepression,HasKidneyStone,HasThyroidDisease,HasFattyLiver,HasCardiacDisease,HasHypertension
0,2.0,44.0,3.0,34.899995,116.0,120.0,19.0,36.652780,1.0,1.0,...,0.0,1.0,4.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,1.0,52.0,1.0,48.075000,99.0,105.0,18.0,28.256990,1.0,1.0,...,0.0,1.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,70.0,2.0,39.416654,89.0,94.0,16.0,20.973709,2.0,99999.0,...,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,2.0,70.0,8.0,51.175000,96.0,106.0,17.0,30.081371,0.0,999.0,...,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
4,2.0,47.0,1.0,34.841659,90.0,97.0,17.5,25.815689,3.0,99.0,...,1.0,1.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3198,2.0,58.0,8.0,40.991661,115.0,112.0,19.0,34.105851,3.0,99.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3199,2.0,50.0,8.0,37.108330,94.0,99.0,16.0,24.878345,3.0,99.0,...,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3200,2.0,65.0,8.0,39.700000,93.0,99.0,16.0,24.609734,3.0,99.0,...,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
3201,1.0,42.0,1.0,40.449995,97.0,96.0,18.0,23.999459,1.0,1.0,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3202,2.0,38.0,3.0,39.508321,92.0,94.0,17.0,26.527905,3.0,99.0,...,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [67]:
y_resampled

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [68]:
df2 = pd.DataFrame(y_resampled, columns=['HasDiabetes'])
df2
#y_resampled=y_resampled.rename(columns = {'0':'HasDiabetes'})

      HasDiabetes
0               0
1               0
2               0
3               0
4               0
...           ...
3198            0
3199            0
3200            0
3201            0
3202            0

[3203 rows x 1 columns]

In [69]:
y_resampled=df2

In [70]:
y_resampled.value_counts()

HasDiabetes
0              2801
1               402
Name: count, dtype: int64

In [71]:
result=[]
result = pd.concat([X_resampled, y_resampled], axis=1, join='inner')

In [72]:
result

,GenderID,Age,LastEduID,MET_Final,WaistCircumference,HipCircumference,WristCircumference,BMI,HasJob_new,Employmentstatus,...,BreadContainerTypeID1,LemonContainerTypeID1,CVD_History,HasDepression,HasKidneyStone,HasThyroidDisease,HasFattyLiver,HasCardiacDisease,HasHypertension,HasDiabetes
0,2.0,44.0,3.0,34.899995,116.0,120.0,19.0,36.652780,1.0,1.0,...,1.0,4.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0
1,1.0,52.0,1.0,48.075000,99.0,105.0,18.0,28.256990,1.0,1.0,...,1.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,1.0,70.0,2.0,39.416654,89.0,94.0,16.0,20.973709,2.0,99999.0,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0
3,2.0,70.0,8.0,51.175000,96.0,106.0,17.0,30.081371,0.0,999.0,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0
4,2.0,47.0,1.0,34.841659,90.0,97.0,17.5,25.815689,3.0,99.0,...,1.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3198,2.0,58.0,8.0,40.991661,115.0,112.0,19.0,34.105851,3.0,99.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
3199,2.0,50.0,8.0,37.108330,94.0,99.0,16.0,24.878345,3.0,99.0,...,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0
3200,2.0,65.0,8.0,39.700000,93.0,99.0,16.0,24.609734,3.0,99.0,...,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0
3201,1.0,42.0,1.0,40.449995,97.0,96.0,18.0,23.999459,1.0,1.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3202,2.0,38.0,3.0,39.508321,92.0,94.0,17.0,26.527905,3.0,99.0,...,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0

In [73]:
import os
os.environ["GIT_PYTHON_REFRESH"] = "quiet"
import git

In [74]:
HasDiabetes= setup(data = result, target = 'HasDiabetes', session_id=123,
                  normalize = True,
                  imputation_type='iterative',
                  transformation = True, 
                  verbose= True,
                  remove_outliers=True,
                  remove_multicollinearity = True, 
                  multicollinearity_threshold = 0.3,
                  normalize_method = 'minmax',
                  feature_selection = True,
                  feature_selection_estimator='lightgbm',
                  train_size = 0.8)

[LightGBM] [Info] Number of positive: 280, number of negative: 2153
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000616 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2661
[LightGBM] [Info] Number of data points in the train set: 2433, number of used features: 45
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.115084 -> initscore=-2.039828
[LightGBM] [Info] Start training from score -2.039828

In [75]:
X_train = get_config('X_train')
X_train

,GenderID,Age,LastEduID,MET_Final,WaistCircumference,HipCircumference,WristCircumference,BMI,HasJob_new,Employmentstatus,...,VegKeepFreezer,BreadContainerTypeID1,LemonContainerTypeID1,CVD_History,HasDepression,HasKidneyStone,HasThyroidDisease,HasFattyLiver,HasCardiacDisease,HasHypertension
273,2.0,66.0,8.0,43.249996,109.0,107.0,20.000000,33.714882,3.0,99.0,...,1.0,5.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1145,1.0,41.0,3.0,35.049992,94.5,101.5,19.500000,25.162134,1.0,1.0,...,1.0,1.0,4.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2630,1.0,57.0,2.0,41.766659,80.0,89.0,16.500000,19.493177,2.0,99999.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3158,1.0,59.0,8.0,44.299999,92.0,97.0,20.200001,23.661438,1.0,1.0,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
915,1.0,63.0,3.0,36.633327,89.0,95.0,19.000000,25.605015,1.0,1.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,1.0,63.0,8.0,47.583328,106.5,101.0,19.200001,28.335932,1.0,1.0,...,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0
1915,2.0,52.0,8.0,50.150002,88.0,90.0,17.000000,26.106562,3.0,99.0,...,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
2063,2.0,63.0,8.0,35.700001,114.0,120.0,18.500000,37.300476,3.0,99.0,...,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1208,2.0,53.0,8.0,38.908325,121.0,123.5,17.500000,36.600117,3.0,99.0,...,0.0,1.0,4.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0
1162,1.0,36.0,4.0,37.966660,106.0,106.0,19.000000,28.408861,1.0,1.0,...,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [76]:
for col in X_train.columns:
    print(col)

GenderID
Age
LastEduID
MET_Final
WaistCircumference
HipCircumference
WristCircumference
BMI
HasJob_new
Employmentstatus
SleepDuration24h1
SleepDurationMidDay1
TV1
AtDeskWork1
Computer1
Eating1
Cooking1
Driving1
Walking1
AerobicExercise1
DrivingHeavyVehicle1
LightAgricultural1
HeavyLaborAgricultJobs1
DPB
SPB
RBC
HGB
FBS
TG
CHOL
SGOT
SGPT
ALP
HDL.C
GGT
LDL_Calc
WSI_total
UseDrugs
UseAlcohol
Pizza
TEACOFFEE
BAVARAGE
Pickle
Oil
SimpleSugar
Vegetables
Nuts
Juice
Fruits
Legumes
Whitemeat
Redmeat
Totalmeat
dairyproduct
Wholegrain
Nutrient FFQ_protein
Total_lipid_fat
GrilledFoodIntID
FriedFoodIntID
PotatoFryTypeID
VegFryTypeID
UsedOilTypeID
ReUseMold
UsedScratchedTeflon
FoodSaltUsedID
OnionFryTypeID
CookingWareID1
VegKeepDried
VegKeepRefrigerator
VegKeepFreezer
BreadContainerTypeID1
LemonContainerTypeID1
CVD_History
HasDepression
HasKidneyStone
HasThyroidDisease
HasFattyLiver
HasCardiacDisease
HasHypertension

In [77]:
X_test = get_config('X_test')
X_test=X_test.reset_index(drop=True)
X_test[:]

,GenderID,Age,LastEduID,MET_Final,WaistCircumference,HipCircumference,WristCircumference,BMI,HasJob_new,Employmentstatus,...,VegKeepFreezer,BreadContainerTypeID1,LemonContainerTypeID1,CVD_History,HasDepression,HasKidneyStone,HasThyroidDisease,HasFattyLiver,HasCardiacDisease,HasHypertension
0,2.0,37.0,3.0,41.133324,90.0,107.0,16.700001,26.914858,3.0,99.0,...,1.0,1.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2.0,66.0,8.0,40.949993,95.0,95.0,18.000000,21.799309,3.0,99.0,...,1.0,1.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2.0,54.0,8.0,45.833324,85.0,95.0,16.500000,23.401922,3.0,99.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,63.0,1.0,54.799992,73.0,82.0,16.500000,15.731337,2.0,99999.0,...,0.0,1.0,4.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,2.0,54.0,1.0,41.724991,111.0,111.0,18.200001,32.258064,3.0,99.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
636,2.0,46.0,2.0,45.008327,78.0,93.0,16.000000,20.795977,3.0,99.0,...,0.0,1.0,4.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
637,2.0,37.0,3.0,36.266663,112.0,113.0,20.500000,35.629955,3.0,99.0,...,1.0,1.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
638,1.0,57.0,2.0,33.533333,78.0,79.0,16.000000,16.359064,0.0,999.0,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
639,2.0,37.0,3.0,39.008320,87.0,99.0,17.500000,23.609459,3.0,99.0,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
640,2.0,48.0,8.0,35.466663,124.0,122.0,22.500000,39.595890,0.0,999.0,...,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0

In [79]:
best_model = compare_models(include = ['xgboost', 'catboost'])

In [80]:
tuned_best_model=tune_model(best_model)

Fitting 10 folds for each of 10 candidates, totalling 100 fits

In [38]:
evaluate_model(tuned_best_model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [39]:
predict_model(tuned_best_model)

,GenderID,Age,LastEduID,MET_Final,WaistCircumference,HipCircumference,WristCircumference,BMI,HasJob_new,Employmentstatus,...,CVD_History,HasDepression,HasKidneyStone,HasThyroidDisease,HasFattyLiver,HasCardiacDisease,HasHypertension,HasDiabetes,prediction_label,prediction_score
4794,1.000000,55.817562,4.795609,35.151226,92.000000,93.306587,17.653294,25.166479,2.000000,99999.000000,...,0.000000,0.897805,0.102195,0.897805,0.0,0.000000,1.000000,1,1,1.0000
2050,2.000000,38.000000,3.000000,37.041664,101.000000,102.000000,16.299999,26.743153,3.000000,99.000000,...,0.000000,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,0,0,0.9996
1599,1.000000,39.000000,3.000000,32.766659,111.000000,110.000000,21.000000,30.029596,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,1.0,0.000000,0.000000,0,0,0.8123
4854,2.000000,39.263756,3.211570,41.236008,99.049347,100.365288,16.342031,28.729939,1.631877,31.961983,...,0.000000,0.000000,0.684061,0.000000,0.0,0.000000,0.315939,1,1,0.9990
606,1.000000,58.000000,8.000000,41.883324,94.000000,93.000000,18.000000,23.808691,1.000000,1.000000,...,0.000000,0.000000,1.000000,0.000000,0.0,0.000000,0.000000,0,0,0.9993
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3631,1.000000,63.323769,2.955604,38.699535,96.000000,92.117485,18.139687,26.651512,0.000000,999.000000,...,0.279372,0.000000,0.000000,0.000000,0.0,0.279372,0.279372,1,1,0.9995
5135,1.336278,50.380455,6.008835,33.562992,103.327446,102.318611,19.986748,29.854837,1.672557,33.955284,...,0.336278,0.000000,0.000000,0.000000,0.0,0.336278,0.663722,1,1,0.9707
2566,2.000000,59.000000,3.000000,38.816666,93.000000,92.000000,18.000000,26.269026,2.000000,99999.000000,...,0.000000,0.000000,1.000000,0.000000,1.0,0.000000,1.000000,1,1,0.9991
1320,1.000000,36.000000,3.000000,35.266659,102.000000,104.000000,20.500000,27.131413,1.000000,1.000000,...,0.000000,0.000000,1.000000,0.000000,0.0,0.000000,0.000000,0,0,0.9996
3661,1.585375,47.414627,5.926873,38.448444,109.682999,111.439117,19.792686,35.937435,2.170749,58.366711,...,0.000000,0.000000,1.000000,0.585375,1.0,0.000000,0.585375,1,1,0.9527

In [ ]:
#blend_knn_et = blend_models(estimator_list=[tuned_best_model,catboost])

In [45]:
print(best_model)

XGBClassifier(base_score=None, booster='gbtree', callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device='cpu', early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=-1, num_parallel_tree=None, ...)

In [46]:
print(tuned_best_model)

XGBClassifier(base_score=None, booster='gbtree', callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device='cpu', early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=-1, num_parallel_tree=None, ...)

In [ ]:
plot_model(tuned_best_model, plot = 'error',save=True)

In [ ]:
X_train = get_config('X_train')
X_train.head(7)

In [ ]:
X_test = get_config('X_test')
X_test=X_test.reset_index(drop=True)
X_test[:]

In [ ]:
interpret_model(tuned_best_model, plot = 'reason', observation = 2, save = True)

In [ ]:
interpret_model(tuned_best_model, plot = 'reason', observation = 4, save = True)

In [ ]:
interpret_model(tuned_best_model, plot = 'reason', observation = 6, save = True)

In [40]:
interpret_model(tuned_best_model, save = True)

In [ ]:
interpret_model(tuned_best_model, plot = 'pdp', feature = 'num_imputer__FBS', save = True)

In [ ]:
interpret_model(tuned_best_model, plot = 'msa', save = True)

In [42]:
save_model(tuned_best_model, 'FinalModel')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('iterative_imputer',
                  TransformerWrapper(exclude=None, include=None,
                                     transformer=IterativeImputer(add_indicator=False,
                                                                  cat_estimator=LGBMClassifier(boosting_type='gbdt',
                                                                                               class_weight=None,
                                                                                               colsample_bytree=1.0,
                                                                                               importance_type='split',
                                                                                               learning_rate=0.1,
                                                                                               max_depth=-1,
                                                                                               min_child_samples=20,
                                                                                               min_child_weight=0.001,
                                                                                               mi...
                                gamma=None, grow_policy=None,
                                importance_type=None,
                                interaction_constraints=None, learning_rate=None,
                                max_bin=None, max_cat_threshold=None,
                                max_cat_to_onehot=None, max_delta_step=None,
                                max_depth=None, max_leaves=None,
                                min_child_weight=None, missing=nan,
                                monotone_constraints=None, multi_strategy=None,
                                n_estimators=None, n_jobs=-1,
                                num_parallel_tree=None, ...))],
          verbose=False),
 'FinalModel.pkl')

In [ ]:
X_train.to_csv('X_train.csv', index=False)
X_test.to_csv('X_test.csv', index=False)

In [ ]:
plot_model(tuned_best_model, plot = 'feature', save = True)

In [ ]:
plot_model(tuned_best_model, plot = 'class_report', save = True)

In [ ]:
plot_model(tuned_best_model, plot = 'auc', save = True)

In [ ]:
plot_model(tuned_best_model, plot = 'threshold', save = True)

In [ ]:
plot_model(tuned_best_model, plot = 'confusion_matrix', save = True)

In [ ]:
plot_model(tuned_best_model, plot = 'boundary', save = True)

In [ ]:
plot_model(tuned_best_model, plot = 'rfe', save = True)

In [ ]:
plot_model(tuned_best_model, plot = 'learning', save = True)

In [ ]:
plot_model(tuned_best_model, plot = 'calibration', save = True)

In [ ]:
plot_model(tuned_best_model, plot = 'vc', save = True)

In [ ]:
plot_model(tuned_best_model, plot = 'feature_all', save = True)

In [48]:
plot_model(tuned_best_model, plot = 'vc', save = True)

'Validation Curve.png'